---
AWSTemplateFormatVersion: 2010-09-09
Description: HERE Location Suite Geocoder integration (Worker Template) for Amazon
  Connect (qs-1ofbdome8)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: HERE Location Suite Configuration
      Parameters:
      - HLSAppId
      - HLSAppCode
    ParameterLabels:
      HLSAppId:
        default: HERE Location Suite Application ID
      HLSAppCode:
        default: HERE Location Suite Application Code
Parameters:
  HLSAppId:
    Description: Your HERE Location Suite App ID.
    Type: String
    MinLength: 6
    MaxLength: 64
  HLSAppCode:
    Description: Your HERE Location Suite App Code.
    Type: String
    MinLength: 6
    MaxLength: 64
Rules:
  RegionSupport:
    Assertions:
    - Assert:
        Fn::Equals:
        - Ref: AWS::Region
        - us-east-1
      AssertDescription: Region must be US East (N. Virginia) - us-east-1
Resources:
  GeocoderTestFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  GeocoderTestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: main.handler
      MemorySize: 128
      Role:
        Fn::GetAtt: GeocoderTestFunctionExecutionRole.Arn
      Runtime: python2.7
      Timeout: 30
      Code:
        S3Bucket: aws-quickstart
        S3Key: connect-integration-here-location-suite/functions/packages/here-integration-geocoder-test/lambda.zip
      Environment:
        Variables:
          appId:
            Ref: HLSAppId
          appCode:
            Ref: HLSAppCode
  GeocoderIntegrationTest:
    Type: Custom::IntegrationTest
    Version: '1.0'
    Properties:
      ServiceToken:
        Fn::GetAtt: GeocoderTestFunction.Arn
  GeocoderExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  GeocoderLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: geocoder-query.lambda_handler
      Runtime: python2.7
      Description: HERE HLS Geocoder API
      MemorySize: 128
      Timeout: 60
      Role:
        Fn::GetAtt: GeocoderExecutionRole.Arn
      Environment:
        Variables:
          appId:
            Ref: HLSAppId
          appCode:
            Ref: HLSAppCode
      Code:
        S3Bucket: aws-quickstart
        S3Key: connect-integration-here-location-suite/functions/packages/here-integration-geocoder/lambda.zip
  GeocoderFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: GeocoderLambdaFunction
      Action: lambda:InvokeFunction
      Principal: connect.amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
Outputs:
  GeocoderLambdaFunction:
    Description: ARN of the Geocoder Lambda function generated by the template.
    Value:
      Fn::GetAtt: GeocoderLambdaFunction.Arn
...
